version: '2'

services:
  webserver:
    build: ./docker/webserver
    image: webdev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
    links:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"      
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=docker
    links:
      - db
  db:
    image: harishdasari1348/webdev_mysql
    ports: 
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      